# Generated by Django 4.1.7 on 2023-03-26 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AzsStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('number', models.IntegerField()),
                ('lat', models.DecimalField(decimal_places=7, max_digits=10)),
                ('lon', models.DecimalField(decimal_places=7, max_digits=10)),
                ('address', models.TextField()),
                ('services', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='BenzineType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('firmid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SummaryForBenzine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost', models.FloatField()),
                ('discont', models.FloatField()),
                ('azs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.azsstation')),
                ('benzine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='server.benzinetype')),
            ],
        ),
        migrations.AddField(
            model_name='benzinetype',
            name='stationtype',
            field=models.ManyToManyField(to='server.stationtype'),
        ),
        migrations.AddField(
            model_name='azsstation',
            name='azstype',
            field=models.ManyToManyField(to='server.stationtype'),
        ),
    ]
